version = 0.1
[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "production-todo-list-aws"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
resolve_s3 = true
image_repositories = []
